# Methanol droplet combustion in microgravity with water condensation
include $(BASILISK)/Makefile.defs

CFLAGS += -O2 \
	-D_MPI=1 \
	-disable-dimensions \
	-DUSE_GSL=1 \
	$(BASILISK_INCLUDES) \
	$(BASILISK_LIBS)

# Global: except LIQUID
CFLAGS_GLOBAL = -DMAXLEVEL=11 \
								-DF_ERR=1.e-4 \
								-DYTOL=1.e-2 \
								-DTTOL=1.e-1 \
								-DUTOL=1.e-2 \
								-DCOMBUSTION=1 \
								-DKINFOLDER=two-step/methanol-water \
								-DLIQFOLDER=LiquidProperties \
								-DDIAMETER=0.5e-3 \
								-DGAS=N2_0.79_O2_0.21 \
								-DSIGMA=0.022 \
								-DEMISSIVITY=0.93 \
								-DTEMPERATURE=300.0 \
								-DTEMPERATURE_DROPLET=300.0 \
								-DPRESSURE=1. \
								-DRADIATION_INTERFACE=0. \
								-DGRAVITY=0. \
								-DFIBER=0.1 \
								-DENVIRONMENT=7.986462e+01 \
								-DSPARK_START=0.0 \
								-DSPARK_TIME=0.004 \
								-DSPARK_VALUE=1e8 \
								-DMAX_DD02=0.005 \
								-DDUMP_EVERY=0.005

# -> Table of cases
CFLAGS_CASE1 = -DLIQUID=CH3OH_1.0_H2O_0.0
CFLAGS_CASE2 = -DLIQUID=CH3OH_0.9_H2O_0.1
CFLAGS_CASE3 = -DLIQUID=CH3OH_0.8_H2O_0.2

# -> Targets
methanolwater-0perc.c: burningdroplet.c
	ln -s burningdroplet.c methanolwater-0perc.c
methanolwater-0perc.s: CFLAGS += $(CFLAGS_GLOBAL) $(CFLAGS_CASE1)
methanolwater-0perc.tst: CFLAGS += $(CFLAGS_GLOBAL) $(CFLAGS_CASE1)
_methanolwater-0perc.c: CFLAGS += $(CFLAGS_GLOBAL) $(CFLAGS_CASE1)

methanolwater-10perc.c: burningdroplet.c
	ln -s burningdroplet.c methanolwater-10perc.c
methanolwater-10perc.s: CFLAGS += $(CFLAGS_GLOBAL) $(CFLAGS_CASE2)
methanolwater-10perc.tst: CFLAGS += $(CFLAGS_GLOBAL) $(CFLAGS_CASE2)
_methanolwater-10perc.c: CFLAGS += $(CFLAGS_GLOBAL) $(CFLAGS_CASE2)

methanolwater-20perc.c: burningdroplet.c
	ln -s burningdroplet.c methanolwater-20perc.c
methanolwater-20perc.s: CFLAGS += $(CFLAGS_GLOBAL) $(CFLAGS_CASE3)
methanolwater-20perc.tst: CFLAGS += $(CFLAGS_GLOBAL) $(CFLAGS_CASE3)
_methanolwater-20perc.c: CFLAGS += $(CFLAGS_GLOBAL) $(CFLAGS_CASE3)

