# N-Heptane combustion from Hara & Kumagai (1994) Symposium (International) on combustion. Vol. 25. No. 1.
include $(BASILISK)/Makefile.defs

CFLAGS += -O2 \
	-D_MPI=1 \
	-disable-dimensions \
	-DUSE_GSL=1 \
	$(BASILISK_INCLUDES) \
	$(BASILISK_LIBS)

# Global: we set everything here cause this is a single simulation
CFLAGS_GLOBAL = -DMAXLEVEL=11 \
								-DYTOL=1.e-2 \
								-DTTOL=1.e-1 \
								-DUTOL=1.e-2 \
								-DCOMBUSTION=1 \
								-DKINFOLDER=two-step/n-heptane \
								-DLIQFOLDER=LiquidProperties \
								-DDIAMETER=0.38e-3 \
								-DLIQUID=NC7H16_1 \
								-DGAS=N2_0.79_O2_0.21
								-DSIGMA=0.022 \
								-DEMISSIVITY=0.93 \
								-DTEMPERATURE=300.0 \
								-DTEMPERATURE_DROPLET=300.0 \
								-DPRESSURE=1. \
								-DRADIATION_INTERFACE=0. \
								-DGRAVITY=0. \
								-DFIBER=0.1 \
								-DENVIRONMENT=7.986462e+01 \
								-DSPARK_START=0.0 \
								-DSPARK_TIME=0.004 \
								-DSPARK_VALUE=1e8 \
								-DMAX_DD02=0.005 \
								-DDUMP_EVERY=0.005


hara.c: burningdroplet.c
	ln -s burningdroplet.c hara.c
hara.s: CFLAGS += $(CFLAGS_GLOBAL)
hara.tst: CFLAGS += $(CFLAGS_GLOBAL)
_hara.c: CFLAGS += $(CFLAGS_GLOBAL)

